// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Event Property documents
 */
interface EventPropertyDocumentData {
  /**
   * Property Image field in *Event Property*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event_property.property_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  property_image: prismic.ImageField<never>;

  /**
   * Title field in *Event Property*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_property.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Event Property*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_property.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Event field in *Event Property*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: event_property.event
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  event: prismic.SelectField<"corporate" | "birthday" | "reception">;

  /**
   * Event Description field in *Event Property*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_property.event_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  event_description: prismic.RichTextField;

  /**
   * Is Available field in *Event Property*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: event_property.is_available
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_available: prismic.BooleanField;
}

/**
 * Event Property document from Prismic
 *
 * - **API ID**: `event_property`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventPropertyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EventPropertyDocumentData>,
    "event_property",
    Lang
  >;

type EventPropertyPageDocumentDataSlicesSlice = EventPropertyDetailsSlice;

/**
 * Content for Event Property Page documents
 */
interface EventPropertyPageDocumentData {
  /**
   * Slice Zone field in *Event Property Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: event_property_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<EventPropertyPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Event Property Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: event_property_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Event Property Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: event_property_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Event Property Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event_property_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Event Property Page document from Prismic
 *
 * - **API ID**: `event_property_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventPropertyPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EventPropertyPageDocumentData>,
    "event_property_page",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | BrandingSlice
  | EventPropertyListingsSlice
  | PropertyListingsSlice
  | TestimonialsSlice
  | HeroSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type RentalDocumentDataSlicesSlice = PropertyDetailsSlice;

/**
 * Content for Rental Property Page documents
 */
interface RentalDocumentData {
  /**
   * Slice Zone field in *Rental Property Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: rental.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<RentalDocumentDataSlicesSlice> /**
   * Meta Title field in *Rental Property Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: rental.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Rental Property Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: rental.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Rental Property Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rental.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Rental Property Page document from Prismic
 *
 * - **API ID**: `rental`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RentalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<RentalDocumentData>, "rental", Lang>;

/**
 * Content for Rental Properties documents
 */
interface RentalPropertiesDocumentData {
  /**
   * Property Image field in *Rental Properties*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rental_properties.property_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  property_image: prismic.ImageField<never>;

  /**
   * Title field in *Rental Properties*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rental_properties.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Rental Properties*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rental_properties.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Lowest Price field in *Rental Properties*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: rental_properties.lowest_price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  lowest_price: prismic.NumberField;

  /**
   * Highest Price field in *Rental Properties*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: rental_properties.highest_price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  highest_price: prismic.NumberField;

  /**
   * Is enabled field in *Rental Properties*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: rental_properties.is_enabled
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_enabled: prismic.BooleanField;
}

/**
 * Rental Properties document from Prismic
 *
 * - **API ID**: `rental_properties`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RentalPropertiesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<RentalPropertiesDocumentData>,
    "rental_properties",
    Lang
  >;

/**
 * Item in *Settings → Nav Links*
 */
export interface SettingsDocumentDataNavLinksItem {
  /**
   * Link field in *Settings → Nav Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Label field in *Settings → Nav Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Settings → Footer Content*
 */
export interface SettingsDocumentDataFooterContentItem {
  /**
   * Branding field in *Settings → Footer Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_content[].branding
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  branding: prismic.KeyTextField;

  /**
   * Declaration field in *Settings → Footer Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_content[].declaration
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  declaration: prismic.KeyTextField;

  /**
   * Copyright field in *Settings → Footer Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_content[].copyright
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Website Icon field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.website_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  website_icon: prismic.ImageField<never>;

  /**
   * Site Name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_name: prismic.KeyTextField;

  /**
   * Site Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_description: prismic.KeyTextField;

  /**
   * Favicon field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.favicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  favicon: prismic.ImageField<never>;

  /**
   * Nav Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  nav_links: prismic.GroupField<Simplify<SettingsDocumentDataNavLinksItem>>;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Footer Content field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_content[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_content: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterContentItem>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | EventPropertyDocument
  | EventPropertyPageDocument
  | HomepageDocument
  | RentalDocument
  | RentalPropertiesDocument
  | SettingsDocument;

/**
 * Primary content in *Branding → Default → Primary*
 */
export interface BrandingSliceDefaultPrimary {
  /**
   * Brand Image field in *Branding → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: branding.default.primary.brand_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  brand_image: prismic.ImageField<never>;
}

/**
 * Default variation for Branding Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BrandingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BrandingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Branding*
 */
type BrandingSliceVariation = BrandingSliceDefault;

/**
 * Branding Shared Slice
 *
 * - **API ID**: `branding`
 * - **Description**: Branding
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BrandingSlice = prismic.SharedSlice<
  "branding",
  BrandingSliceVariation
>;

/**
 * Primary content in *EventPropertyDetails → Default → Primary*
 */
export interface EventPropertyDetailsSliceDefaultPrimary {
  /**
   * Event Property field in *EventPropertyDetails → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: event_property_details.default.primary.event_property
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  event_property: ContentRelationshipFieldWithData<
    [
      {
        id: "event_property";
        fields: [
          "property_image",
          "title",
          "description",
          "event",
          "event_description",
          "is_available",
        ];
      },
    ]
  >;
}

/**
 * Default variation for EventPropertyDetails Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventPropertyDetailsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventPropertyDetailsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EventPropertyDetails*
 */
type EventPropertyDetailsSliceVariation = EventPropertyDetailsSliceDefault;

/**
 * EventPropertyDetails Shared Slice
 *
 * - **API ID**: `event_property_details`
 * - **Description**: EventPropertyDetails
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventPropertyDetailsSlice = prismic.SharedSlice<
  "event_property_details",
  EventPropertyDetailsSliceVariation
>;

/**
 * Item in *EventPropertyListings → Default → Primary → Event Properties*
 */
export interface EventPropertyListingsSliceDefaultPrimaryEventPropertiesItem {
  /**
   * Event Property field in *EventPropertyListings → Default → Primary → Event Properties*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: event_property_listings.default.primary.event_properties[].event_property
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  event_property: ContentRelationshipFieldWithData<
    [
      {
        id: "event_property";
        fields: [
          "property_image",
          "title",
          "description",
          "event",
          "event_description",
          "is_available",
        ];
      },
    ]
  >;
}

/**
 * Primary content in *EventPropertyListings → Default → Primary*
 */
export interface EventPropertyListingsSliceDefaultPrimary {
  /**
   * Heading field in *EventPropertyListings → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_property_listings.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Event Properties field in *EventPropertyListings → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: event_property_listings.default.primary.event_properties[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  event_properties: prismic.GroupField<
    Simplify<EventPropertyListingsSliceDefaultPrimaryEventPropertiesItem>
  >;
}

/**
 * Default variation for EventPropertyListings Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventPropertyListingsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventPropertyListingsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EventPropertyListings*
 */
type EventPropertyListingsSliceVariation = EventPropertyListingsSliceDefault;

/**
 * EventPropertyListings Shared Slice
 *
 * - **API ID**: `event_property_listings`
 * - **Description**: EventPropertyListings
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventPropertyListingsSlice = prismic.SharedSlice<
  "event_property_listings",
  EventPropertyListingsSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Hero Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Text Hex Color Code field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.text_hex_color_code
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text_hex_color_code: prismic.KeyTextField;

  /**
   * Hero Caption field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_caption: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *PropertyDetails → Default → Primary*
 */
export interface PropertyDetailsSliceDefaultPrimary {
  /**
   * Property Details field in *PropertyDetails → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: property_details.default.primary.property_details
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  property_details: ContentRelationshipFieldWithData<
    [
      {
        id: "rental_properties";
        fields: [
          "property_image",
          "title",
          "description",
          "lowest_price",
          "highest_price",
          "is_enabled",
        ];
      },
    ]
  >;
}

/**
 * Default variation for PropertyDetails Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PropertyDetailsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PropertyDetailsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PropertyDetails*
 */
type PropertyDetailsSliceVariation = PropertyDetailsSliceDefault;

/**
 * PropertyDetails Shared Slice
 *
 * - **API ID**: `property_details`
 * - **Description**: PropertyDetails
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PropertyDetailsSlice = prismic.SharedSlice<
  "property_details",
  PropertyDetailsSliceVariation
>;

/**
 * Item in *PropertyListings → Default → Primary → Rental Property Listings*
 */
export interface PropertyListingsSliceDefaultPrimaryRentalPropertyListingsItem {
  /**
   * Rental Property field in *PropertyListings → Default → Primary → Rental Property Listings*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: property_listings.default.primary.rental_property_listings[].rental_property
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  rental_property: ContentRelationshipFieldWithData<
    [
      {
        id: "rental_properties";
        fields: [
          "property_image",
          "title",
          "description",
          "lowest_price",
          "highest_price",
          "is_enabled",
        ];
      },
    ]
  >;
}

/**
 * Primary content in *PropertyListings → Default → Primary*
 */
export interface PropertyListingsSliceDefaultPrimary {
  /**
   * Heading field in *PropertyListings → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property_listings.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Rental Property Listings field in *PropertyListings → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: property_listings.default.primary.rental_property_listings[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  rental_property_listings: prismic.GroupField<
    Simplify<PropertyListingsSliceDefaultPrimaryRentalPropertyListingsItem>
  >;
}

/**
 * Default variation for PropertyListings Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PropertyListingsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PropertyListingsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PropertyListings*
 */
type PropertyListingsSliceVariation = PropertyListingsSliceDefault;

/**
 * PropertyListings Shared Slice
 *
 * - **API ID**: `property_listings`
 * - **Description**: PropertyListings
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PropertyListingsSlice = prismic.SharedSlice<
  "property_listings",
  PropertyListingsSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → Testimonial*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialItem {
  /**
   * Avatar field in *Testimonials → Default → Primary → Testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].avatar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Author field in *Testimonials → Default → Primary → Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].author
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * Quote field in *Testimonials → Default → Primary → Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].quote
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  quote: prismic.KeyTextField;

  /**
   * Rating field in *Testimonials → Default → Primary → Testimonial*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].rating
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  rating: prismic.NumberField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Testimonial field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonial: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      EventPropertyDocument,
      EventPropertyDocumentData,
      EventPropertyPageDocument,
      EventPropertyPageDocumentData,
      EventPropertyPageDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      RentalDocument,
      RentalDocumentData,
      RentalDocumentDataSlicesSlice,
      RentalPropertiesDocument,
      RentalPropertiesDocumentData,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavLinksItem,
      SettingsDocumentDataFooterContentItem,
      AllDocumentTypes,
      BrandingSlice,
      BrandingSliceDefaultPrimary,
      BrandingSliceVariation,
      BrandingSliceDefault,
      EventPropertyDetailsSlice,
      EventPropertyDetailsSliceDefaultPrimary,
      EventPropertyDetailsSliceVariation,
      EventPropertyDetailsSliceDefault,
      EventPropertyListingsSlice,
      EventPropertyListingsSliceDefaultPrimaryEventPropertiesItem,
      EventPropertyListingsSliceDefaultPrimary,
      EventPropertyListingsSliceVariation,
      EventPropertyListingsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      PropertyDetailsSlice,
      PropertyDetailsSliceDefaultPrimary,
      PropertyDetailsSliceVariation,
      PropertyDetailsSliceDefault,
      PropertyListingsSlice,
      PropertyListingsSliceDefaultPrimaryRentalPropertyListingsItem,
      PropertyListingsSliceDefaultPrimary,
      PropertyListingsSliceVariation,
      PropertyListingsSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
