// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  branding: dynamic(() => import("./Branding")),
  event_property_details: dynamic(() => import("./EventPropertyDetails")),
  event_property_listings: dynamic(() => import("./EventPropertyListings")),
  hero: dynamic(() => import("./Hero")),
  property_details: dynamic(() => import("./PropertyDetails")),
  property_listings: dynamic(() => import("./PropertyListings")),
  testimonials: dynamic(() => import("./Testimonials")),
};
