// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  property_listings: dynamic(() => import("./PropertyListings")),
  testimonials: dynamic(() => import("./Testimonials")),
};
